### ISSUE TITLE
Android13卡在积分界面

### ISSUE THREAD

**Issue by libo-1988** [songjiang951130/auto_xuexiqiangguo#3]
![Screenshot_20221004_220633](https://user-images.githubusercontent.com/68573425/193841577-52c2bdbd-e926-4f6d-8835-5a83ebb360a2.jpg)
Android13 卡在积分界面报错

**Comment by songjiang951130** [comment]
> ![Screenshot_20221004_220633](https://user-images.githubusercontent.com/68573425/193841577-52c2bdbd-e926-4f6d-8835-5a83ebb360a2.jpg) Android13 卡在积分界面报错

2.33 没这个问题的

**Comment by songjiang951130** [comment]
我最近又更新了一些东西，可以试试，新的代码

**Comment by libo-1988** [comment]
> 我最近又更新了一些东西，可以试试，新的代码

好的，谢谢，辛苦了，Android13问题有点多，，老版本学习强国一直网络超超时，我换个手机试试。

**Comment by songjiang951130** [comment]
> > 我最近又更新了一些东西，可以试试，新的代码
> 
> 好的，谢谢，辛苦了，Android13问题有点多，，老版本学习强国一直网络超超时，我换个手机试试。

https://github.com/dundunnp/auto_xuexiqiangguo/blob/version-15.6/%E5%AE%89%E8%A3%85%E5%8C%85/v2.33.0 用这个包试试

**Comment by libo-1988** [comment]
> > > 我最近又更新了一些东西，可以试试，新的代码
> > 
> > 
> > 好的，谢谢，辛苦了，Android13问题有点多，，老版本学习强国一直网络超超时，我换个手机试试。
> 
> https://github.com/dundunnp/auto_xuexiqiangguo/blob/version-15.6/%E5%AE%89%E8%A3%85%E5%8C%85/v2.33.0 用这个包试试

应该不是APP版本问题，在10月3日之前可以用，就是答题全选A，更新之后就不能用了。

**Comment by songjiang951130** [comment]
> > > > 我最近又更新了一些东西，可以试试，新的代码
> > > 
> > > 
> > > 好的，谢谢，辛苦了，Android13问题有点多，，老版本学习强国一直网络超超时，我换个手机试试。
> > 
> > 
> > https://github.com/dundunnp/auto_xuexiqiangguo/blob/version-15.6/%E5%AE%89%E8%A3%85%E5%8C%85/v2.33.0 用这个包试试
> 
> 应该不是APP版本问题，在10月3日之前可以用，就是答题全选A，更新之后就不能用了。

全选a是ocr 错误或者，ocr出的结果找不到题，他就默认选的第一个了。我这个修复了很多问题，还是能拿第一的

**Comment by libo-1988** [comment]
> > > > > 我最近又更新了一些东西，可以试试，新的代码
> > > > 
> > > > 
> > > > 好的，谢谢，辛苦了，Android13问题有点多，，老版本学习强国一直网络超超时，我换个手机试试。
> > > 
> > > 
> > > https://github.com/dundunnp/auto_xuexiqiangguo/blob/version-15.6/%E5%AE%89%E8%A3%85%E5%8C%85/v2.33.0 用这个包试试
> > 
> > 
> > 应该不是APP版本问题，在10月3日之前可以用，就是答题全选A，更新之后就不能用了。
> 
> 全选a是ocr 错误或者，ocr出的结果找不到题，他就默认选的第一个了。我这个修复了很多问题，还是能拿第一的

谢谢修复，辛苦了
