### ISSUE TITLE
复制到脚本下，从哪里复制代码

### ISSUE THREAD

**Issue by Sakurasmr** [songjiang951130/auto_xuexiqiangguo#4]
---

**软件版本信息**
 - 学习强国版本: [e.g. 2.33.0]

第一步就没成功，翻来覆去的没看到代码，我太失败了

**Comment by libo-1988** [comment]
autox打开后根目录会生成一个叫脚本的文件夹，然后把整个项目打包下载下来，解压后整个文件夹都放进脚本的文件夹。

**Comment by songjiang951130** [comment]
> **软件版本信息**
> 
> * 学习强国版本: [e.g. 2.33.0]
> 
> 第一步就没成功，翻来覆去的没看到代码，我太失败了

就是下载解压到 脚本 文件夹下，你是一点autojs基础都没有啊
